import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import { Header } from "./components/header";
import { SidebarProvider } from "@/components/ui/sidebar";
import BottomNavbar from "./components/bottomNavbar";
import { AppSidebar } from "./components/features/appSidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased pb-14 lg:pb-0`}
            >
                <SidebarProvider>
                    <div className="lg:hidden">
                        <AppSidebar />
                    </div>
                    <div className="flex flex-col w-full">
                        <Header />
                        {children}
                    </div>
                </SidebarProvider>
                <Footer />
                <div className="lg:hidden">
                    <BottomNavbar />
                </div>
            </body>
        </html>
    );
}
